name: Pull Request Check
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - .gitignore
env:
  GO_VERSION: 1.23.1
jobs:
  lint:
    name: 'Code linters'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Go ${{ env.GO_VERSION }}'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: 'Check out project files'
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: false
      - name: 'Prepare environment'
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: 'Run code linters'
        run: |
          GO111MODULE=on make lint
  unit-tests:
    name: 'Unit tests in ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    env:
      QUORUM_IGNORE_TEST_PACKAGES: github.com/ethereum/go-ethereum/les,github.com/ethereum/go-ethereum/les/flowcontrol,github.com/ethereum/go-ethereum/mobile
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Setup Go ${{ env.GO_VERSION }}'
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: 'Check out project files'
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: recursive
      - name: 'Prepare environment'
        run: |
          # https://github.com/actions/virtual-environments/issues/798
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: 'Run unit tests'
        run: |
          make test
